### ISSUE TITLE
Failed to depoly with OPTS="MODEL_SERVER_DEPLOY TRAINER_DEPLOY"

### ISSUE THREAD

**Issue by Yanbo0101** [sustainable-computing-io/kepler-model-server#130]
### What happened?

when I execute 
```shell
make build-manifest OPTS="PROMETHEUS_DEPLOY MODEL_SERVER_DEPLOY TRAINER_DEPLOY"
cd _output/generated-manifest
kubectl apply -f deployment.yaml
``` 
The pod kepler-model-server is always  CrashLoopBackOff 
```shell
kepler-model-server-7b9f8fb498-wqlr9   1/2     CrashLoopBackOff   6 (3m17s ago)   9m35s
``` 
Then I check the pod and log
```shell
kubectl describe pods kepler-model-server-7b9f8fb498-wqlr9 -n kepler

Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Pulled     31s                kubelet            Container image "quay.io/sustainable_computing_io/kepler_model_server:v0.6" already present on machine
  Normal   Created    31s                kubelet            Created container server-api
  Normal   Started    31s                kubelet            Started container server-api
  Normal   Scheduled  29s                default-scheduler  Successfully assigned kepler/kepler-model-server-5f8787999f-q9qtn to cpio-sprqct-prc5
  Normal   Pulled     14s (x3 over 31s)  kubelet            Container image "quay.io/sustainable_computing_io/kepler_model_server:v0.6" already present on machine
  Normal   Created    14s (x3 over 31s)  kubelet            Created container online-trainer
  Normal   Started    13s (x3 over 31s)  kubelet            Started container online-trainer
  Warning  BackOff    13s (x3 over 29s)  kubelet            Back-off restarting failed container
``` 
```shell
kubectl logs kepler-model-server-5f8787999f-q9qtn -n kepler
Defaulted container "server-api" out of: server-api, online-trainer
try downloading archieved pipeline from URL: https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-db/main/models/Linux-4.15.0-213-generic-x86_64_v0.6.zip
<Response [200]>
initial pipeline is loaded to /data/models/default
 * Serving Flask app 'model_server' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8100
 * Running on http://10.244.1.43:8100
Press CTRL+C to quit
``` 
It seems that there is no problem with the server-api, but I'm not sure if the error came from online-train or sidecar? Then I try to exec pod with 
/
```shell
kubectl exec -it kepler-model-server-5f8787999f-q9qtn -n kepler bash
python3.8 src/train/online_trainer.py
Traceback (most recent call last):
  File "online_trainer.py", line 46, in <module>
    profile_pipeline, non_profile_pipeline = initial_pipelines()
  File "online_trainer.py", line 38, in initial_pipelines
    target_energy_sources = target_energy_sources.keys()
UnboundLocalError: local variable 'target_energy_sources' referenced before assignment
``` 
Is there some wrong with online-train?

### What did you expect to happen?

.

### How can we reproduce it (as minimally and precisely as possible)?

make build-manifest OPTS="PROMETHEUS_DEPLOY MODEL_SERVER_DEPLOY TRAINER_DEPLOY"
cd _output/generated-manifest
kubectl apply -f deployment.yaml

### Kepler image tag

<details>

</details>

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider or bare metal

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Kepler deployment config

<details>

For on kubernetes:
```console
$ KEPLER_NAMESPACE=kepler

# provide kepler configmap
$ kubectl get configmap kepler-cfm -n ${KEPLER_NAMESPACE} 
# paste output here

# provide kepler deployment description
$ kubectl describe deployment kepler-exporter -n ${KEPLER_NAMESPACE} 
```

For standalone:
# put your Kepler command argument here

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sunya-ch** [comment]
It is a bug in the code

need to change from `target_energy_sources` to `PowerSourceMap` as below.

```python
def initial_pipelines():
    target_energy_sources = PowerSourceMap.keys()
```

online_trainer has not included in the integration yet. We need to add that to confirm functionality.

**Comment by sunya-ch** [comment]
@Yanbo0101 Do you want to try fixing it with PR? Otherwise, I can work on that tomorrow.

**Comment by Yanbo0101** [comment]
> It is a bug in the code
> 
> need to change from `target_energy_sources` to `PowerSourceMap` as below.
> 
> ```python
> def initial_pipelines():
>     target_energy_sources = PowerSourceMap.keys()
> ```
> 
> online_trainer has not included in the integration yet. We need to add that to confirm functionality.

Will online_trainer  integrate in kepler-release-v0.6?

**Comment by Yanbo0101** [comment]
> @Yanbo0101 Do you want to try fixing it with PR? Otherwise, I can work on that tomorrow.

Sure, I will do it.
