### ISSUE TITLE
online trainer failed

### ISSUE THREAD

**Issue by rootfs** [sustainable-computing-io/kepler-model-server#61]
This is the log
```
mount path:  /mnt
Successfully load https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/AbsComponentPower/Full/KerasCompFullPipeline/metadata.json to /data/models/AbsComponentPower/Full/KerasCompFullPipeline/metadata.json
Successfully load https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/AbsComponentPower/Full/KerasCompFullPipeline.zip to /data/models/AbsComponentPower/Full/KerasCompFullPipeline.zip
Failed to load https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/AbsComponentPower/WorkloadOnly/KerasCompFullPipeline/metadata.json to /data/models/AbsComponentPower/WorkloadOnly/KerasCompFullPipeline/metadata.json: 404:
Failed to load https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/AbsComponentPower/CounterOnly/KerasCompFullPipeline/metadata.json to /data/models/AbsComponentPower/CounterOnly/KerasCompFullPipeline/metadata.json: 404:
Failed to load https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/AbsComponentPower/CgroupOnly/KerasCompFullPipeline/metadata.json to /data/models/AbsComponentPower/CgroupOnly/KerasCompFullPipeline/metadata.json: 404:
Failed to load https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/AbsComponentPower/BPFOnly/KerasCompFullPipeline/metadata.json to /data/models/AbsComponentPower/BPFOnly/KerasCompFullPipeline/metadata.json: 404:
Failed to load https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/AbsComponentPower/KubeletOnly/KerasCompFullPipeline/metadata.json to /data/models/AbsComponentPower/KubeletOnly/KerasCompFullPipeline/metadata.json: 404:
Failed to load https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/AbsComponentPower/Unknown/KerasCompFullPipeline/metadata.json to /data/models/AbsComponentPower/Unknown/KerasCompFullPipeline/metadata.json: 404:
Successfully load https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/AbsComponentModelWeight/Full/KerasCompWeightFullPipeline/metadata.json to /data/models/AbsComponentModelWeight/Full/KerasCompWeightFullPipeline/metadata.json
Failed to load /data/models/AbsComponentModelWeight/Full/KerasCompWeightFullPipeline/KerasCompWeightFullPipeline.json to /data/models/AbsComponentModelWeight/Full/KerasCompWeightFullPipeline/KerasCompWeightFullPipeline.json: Invalid URL '/data/models/AbsComponentModelWeight/Full/KerasCompWeightFullPipeline/KerasCompWeightFullPipeline.json': No scheme supplied. Perhaps you meant http:///data/models/AbsComponentModelWeight/Full/KerasCompWeightFullPipeline/KerasCompWeightFullPipeline.json?:
Failed to load https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/AbsComponentModelWeight/WorkloadOnly/KerasCompWeightFullPipeline/metadata.json to /data/models/AbsComponentModelWeight/WorkloadOnly/KerasCompWeightFullPipeline/metadata.json: 404:
Failed to load https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/AbsComponentModelWeight/CounterOnly/KerasCompWeightFullPipeline/metadata.json to /data/models/AbsComponentModelWeight/CounterOnly/KerasCompWeightFullPipeline/metadata.json: 404:
Failed to load https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/AbsComponentModelWeight/CgroupOnly/KerasCompWeightFullPipeline/metadata.json to /data/models/AbsComponentModelWeight/CgroupOnly/KerasCompWeightFullPipeline/metadata.json: 404:
Failed to load https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/AbsComponentModelWeight/BPFOnly/KerasCompWeightFullPipeline/metadata.json to /data/models/AbsComponentModelWeight/BPFOnly/KerasCompWeightFullPipeline/metadata.json: 404:
Failed to load https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/AbsComponentModelWeight/KubeletOnly/KerasCompWeightFullPipeline/metadata.json to /data/models/AbsComponentModelWeight/KubeletOnly/KerasCompWeightFullPipeline/metadata.json: 404:
Failed to load https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/AbsComponentModelWeight/Unknown/KerasCompWeightFullPipeline/metadata.json to /data/models/AbsComponentModelWeight/Unknown/KerasCompWeightFullPipeline/metadata.json: 404:
Failed to load https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/DynComponentPower/Full/ScikitMixed/metadata.json to /data/models/DynComponentPower/Full/ScikitMixed/metadata.json: 404:
Failed to load https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/DynComponentPower/WorkloadOnly/ScikitMixed/metadata.json to /data/models/DynComponentPower/WorkloadOnly/ScikitMixed/metadata.json: 404:
Successfully load https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/DynComponentPower/CounterOnly/ScikitMixed/metadata.json to /data/models/DynComponentPower/CounterOnly/ScikitMixed/metadata.json
Successfully load https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/DynComponentPower/CounterOnly/ScikitMixed.zip to /data/models/DynComponentPower/CounterOnly/ScikitMixed.zip
Successfully load https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/DynComponentPower/CgroupOnly/ScikitMixed/metadata.json to /data/models/DynComponentPower/CgroupOnly/ScikitMixed/metadata.json
Successfully load https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/DynComponentPower/CgroupOnly/ScikitMixed.zip to /data/models/DynComponentPower/CgroupOnly/ScikitMixed.zip
Successfully load https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/DynComponentPower/BPFOnly/ScikitMixed/metadata.json to /data/models/DynComponentPower/BPFOnly/ScikitMixed/metadata.json
Successfully load https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/DynComponentPower/BPFOnly/ScikitMixed.zip to /data/models/DynComponentPower/BPFOnly/ScikitMixed.zip
Failed to load https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/DynComponentPower/KubeletOnly/ScikitMixed/metadata.json to /data/models/DynComponentPower/KubeletOnly/ScikitMixed/metadata.json: 404:
Failed to load https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/DynComponentPower/Unknown/ScikitMixed/metadata.json to /data/models/DynComponentPower/Unknown/ScikitMixed/metadata.json: 404:
Traceback (most recent call last):
  File "online_trainer.py", line 27, in <module>
    pipeline_module = importlib.import_module('train.pipelines.{}.pipe'.format(pipeline_name))
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/train/pipelines/KerasFullPipeline/pipe.py", line 10, in <module>
    from pipeline import TrainPipeline
  File "/train/pipeline.py", line 61, in <module>
    os.mkdir(group_path)
FileExistsError: [Errno 17] File exists: '/data/models/DynComponentModelWeight/Full'

```

**Comment by KaiyiLiu1234** [comment]
Will conduct testing this week.

**Comment by sunya-ch** [comment]
Should be added to unit test.
