### ISSUE TITLE
online trainer crashed with error: cannot import name 'NODE_STAT_QUERY' from 'prom.query' (/prom/query.py)

### ISSUE THREAD

**Issue by rootfs** [sustainable-computing-io/kepler-model-server#98]
```console
# oc logs kepler-model-server-57758d548b-mql4q online-trainer
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-peg40l2e because the default path (/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
2023-05-23 21:48:05.652598: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-05-23 21:48:05.656329: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-05-23 21:48:05.656352: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
mount path:  /mnt
Initial Model Names: {'AbsComponentModelWeight': 'KerasCompWeightFullPipeline', '\t\t\tAbsComponentPower': 'KerasCompFullPipeline', '\t\t\tDynComponentPower': 'ScikitMixed'}
Successfully load https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/AbsComponentModelWeight/Full/KerasCompWeightFullPipeline/metadata.json to /mnt/models/AbsComponentModelWeight/Full/KerasCompWeightFullPipeline/metadata.json
Successfully load https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/AbsComponentModelWeight/Full/KerasCompWeightFullPipeline/KerasCompWeightFullPipeline.json to /mnt/models/AbsComponentModelWeight/Full/KerasCompWeightFullPipeline/KerasCompWeightFullPipeline.json
Failed to load https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/AbsComponentModelWeight/WorkloadOnly/KerasCompWeightFullPipeline/metadata.json to /mnt/models/AbsComponentModelWeight/WorkloadOnly/KerasCompWeightFullPipeline/metadata.json: 404
Failed to load https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/AbsComponentModelWeight/CounterOnly/KerasCompWeightFullPipeline/metadata.json to /mnt/models/AbsComponentModelWeight/CounterOnly/KerasCompWeightFullPipeline/metadata.json: 404
Failed to load https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/AbsComponentModelWeight/CgroupOnly/KerasCompWeightFullPipeline/metadata.json to /mnt/models/AbsComponentModelWeight/CgroupOnly/KerasCompWeightFullPipeline/metadata.json: 404
Failed to load https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/AbsComponentModelWeight/BPFOnly/KerasCompWeightFullPipeline/metadata.json to /mnt/models/AbsComponentModelWeight/BPFOnly/KerasCompWeightFullPipeline/metadata.json: 404
Failed to load https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/AbsComponentModelWeight/KubeletOnly/KerasCompWeightFullPipeline/metadata.json to /mnt/models/AbsComponentModelWeight/KubeletOnly/KerasCompWeightFullPipeline/metadata.json: 404
Failed to load https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/AbsComponentModelWeight/IRQOnly/KerasCompWeightFullPipeline/metadata.json to /mnt/models/AbsComponentModelWeight/IRQOnly/KerasCompWeightFullPipeline/metadata.json: 404
Failed to load https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/AbsComponentModelWeight/CounterIRQCombined/KerasCompWeightFullPipeline/metadata.json to /mnt/models/AbsComponentModelWeight/CounterIRQCombined/KerasCompWeightFullPipeline/metadata.json: 404
Failed to load https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/AbsComponentModelWeight/Unknown/KerasCompWeightFullPipeline/metadata.json to /mnt/models/AbsComponentModelWeight/Unknown/KerasCompWeightFullPipeline/metadata.json: 404
Traceback (most recent call last):
  File "online_trainer.py", line 27, in <module>
    pipeline_module = importlib.import_module('train.pipelines.{}.pipe'.format(pipeline_name))
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/train/pipelines/KerasFullPipeline/pipe.py", line 22, in <module>
    from prom.query import NODE_STAT_QUERY
ImportError: cannot import name 'NODE_STAT_QUERY' from 'prom.query' (/prom/query.py)
```

NODE_STAT_QUERY was removed in commit 85db8ab644e4270ebedf52c6af2762777be598e0

**Comment by sunya-ch** [comment]
Should be deprecated.
